<?php
//RECOGEMOS EL AÑO PARA RECOGER EL NOMBRE Y LA INFORMACION DE TODAS LAS CARRERAS DE UNA TEMPORARDA, EN LA URL PARA PODER OBTENER LA API
$year = $_POST['year'];

// URL DE LA API PARA RECOGER LA INFORMACION DE LAS CARRERAS DE UNA TEMPORADA
$url = 'https://ergast.com/api/f1/' . $year . '.json';

// OBTENER LOS DATOS DE LA URL Y GUARDARLO EN EL ARRAY DATA
$data = file_get_contents($url);

//MANDAR LOS DATOS PARA RECOGERLOS POSTERIORMENTE EN LA RESPUESTA DEL AJAX
echo $data;
?>