<?php
//RECOGEMOS EL AÑO PARA PODER FILTRAR Y BUSCAR EL AÑO DE LA CLASIFICAION DE PILOTOS, EN LA URL PARA PODER OBTENER LA API
$year = $_POST['year'];

// URL DE LA API PARA RECOGER LOS PILOTOS POR AÑO
$url = 'https://ergast.com/api/f1/' . $year . '/driverStandings.json';

// OBTENER LOS DATOS DE LA URL Y GUARDARLO EN EL ARRAY DATA
$data = file_get_contents($url);

//MANDAR LOS DATOS PARA RECOGERLOS POSTERIORMENTE EN LA RESPUESTA DEL AJAX
echo $data;
?>